[package]
name = "fastdfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
anyhow = "1.0.69"
md5 = "0.7.0"
tokio = "1.25.0"
md5-rs = "0.1.5"
