[package]
name = "fastdfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
anyhow = "1.0.69"
tokio = "1.25.0"
md-5 = "0.10.5"
rand = "0.8.5"
base64 = "0.21.0"
